config/routes.rb
Rails.application.routes.draw do

  resources :comentarios

  root 'inicio#index'

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:nombre, :email, :texto)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
    @comentario = Comentario.new
    @comentarios = Comentario.all.order('created_at DESC').take(5)
    @count_comentarios = Comentario.all.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
        <% @comentario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :texto %><br>
    <%= f.text_area :texto, size: "60x12", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Enviar", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <h1>Mostrando Comentarios</h1>
  
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Email</th>
        <th>Texto</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @comentarios.each do |comentario| %>
        <tr>
          <td><%= comentario.nombre %></td>
          <td><%= comentario.email %></td>
          <td><%= comentario.texto %></td>
          <td><%= link_to 'Show', comentario %></td>
          <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
          <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <ul>
    <li><%= link_to 'Agregar Comentario', new_comentario_path %></li>
    <li><%= link_to "Inicio", controller: "inicio", action: "index" %></li>
  </ul>
</div>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @comentario.nombre %>
</p>

<p>
  <strong>Email:</strong>
  <%= @comentario.email %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @comentario.texto %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/inicio/index.html.erb
<div class="container">
  <header class="row row-common row-1" id="row-bienvenido">
    <div class="col-md-12">
      <h1>Bienvenido</h1>
      <p>Este es un hola mundo, porque los Hola Mundo son realmente innovadores y únicos en su clase. Creo que jamás había visto un Hola Mundo hasta ahora, me siento único y especial.</p>
    </div>
  </header>
  
  <div class="row row-common row-2" id="row-comentarios">
    <div class="col-md-12">
      <h2 class="rotulo">Comentarios <span class="ayuda">(Mostrando 5 de <%= @count_comentarios.to_s %>)</span>:</h2>
  
      <div class="table-responsive">
        <table class="table table-stripped table-hover">
          <thead>
            <tr>
              <th class="columna nombre">Nombre</th>
              <th class="columna email">Email</th>
              <th class="columna texto">Texto</th>
              <th class="columna acciones" colspan="3"></th>
            </tr>
          </thead>
        
          <tbody>
            <% @comentarios.each do |comentario| %>
              <tr>
                <td><%= comentario.nombre %></td>
                <td><%= comentario.email %></td>
                <td><%= comentario.texto %></td>
                <td><%= link_to 'Mostrar', comentario %></td>
                <td><%= link_to 'Editar', edit_comentario_path(comentario) %></td>
                <td><%= link_to 'Eliminar <span class="glyphicon glyphicon-trash"></span>'.html_safe, comentario, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      
      <% if @count_comentarios > 1 %>
        <% @verbo_comentarios = "comentarios" %>
      <% else %>
        <% @verbo_comentarios = "comentario" %>
      <% end %>
      
      <%= link_to "Ver " + @count_comentarios.to_s + " " + @verbo_comentarios, { :controller => "comentarios", :action => "index" }, { :class => "btn btn-default"} %>
      
      <span class="clearfix"></span>
      <div class="comentario-new col-md-8 col-md-offset-2">
          <h3 class="rotulo">Dejar un comentario nuevo</h3>
          <%= render 'comentarios/form' %>
      </div>
      
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unab1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
  <%= yield %>
</div>
</body>
</html>